### ISSUE TITLE
Rename branches to Polymer1 and Polymer2

### ISSUE THREAD

**Issue by alshakero** [Starcounter/StarcounterClientFiles#19]
Isn't it misleading that the branches are called master and master2.4? They're both for 2.4 and can't run on 2.3. This might create confusion and break the pattern for the other apps.

Also `master` doesn't carry any information within, `Polymer1` and `Polymer2` do. 

WDYT @warpech @tomalec

**Comment by warpech** [comment]
Thanks for bringing up the idea. 

I think that `Polymer1` and `Polymer2` are not good names, because our long term strategy is not to tie to a specific framework.

I have renamed the master branch to `1.x` and master-2.4 to `2.x` according to the version number of SCF. I think it will be better this way.

**Comment by alshakero** [comment]
Great thanks!
